unbind C-b
set -g prefix C-]

set -g status off

set -g mouse off

set -g escape-time 10

setw -g mode-keys vi
bind C-c copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xsel -bi'

bind C-h split-window -v -c '#{pane_current_path}'
bind C-v split-window -h -c '#{pane_current_path}'
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind C-w new-window
bind -n M-q previous-window
bind -n M-w next-window
