#!/usr/bin/env bash
set -ex
cd $(dirname $0)
sudo apt update

# build-essential
sudo apt install build-essential

# git
sudo apt install git

# curl
sudo apt install curl

# go
if ! [ -f /usr/local/go/bin/go ]; then
    curl -LO https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
    rm go1.24.1.linux-amd64.tar.gz
fi

# cargo
if ! [ -f ~/.cargo/bin/cargo ]; then
    curl https://sh.rustup.rs -sSf | sh
fi

# uv
if ! [ -f ~/.local/bin/uv ]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

# ruby
sudo apt install ruby-full

# ghq
/usr/local/go/bin/go install github.com/x-motemen/ghq@latest

# lazygit
/usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

# helix
~/go/bin/ghq get https://github.com/helix-editor/helix
pushd ~/ghq/github.com/helix-editor/helix > /dev/null
git pull
~/.cargo/bin/cargo install --path helix-term --locked
mkdir -p ~/.config/helix/
ln -Tfs $PWD/runtime ~/.config/helix/runtime
popd > /dev/null

# wireguard
sudo apt install wireguard

# cloc
sudo apt install cloc

# tree
sudo apt install tree

# xsel
sudo apt install xsel

# z
~/go/bin/ghq get https://github.com/rupa/z

# memo
if ! [ -d ~/memo ]; then
    pushd ~ > /dev/null
    git clone git@github.com:tm99hjkllogseq/memo
    cd memo
    git config user.name "tm99hjkllogseq"
    git config user.email "tm99hjkllogseq@gmail.com"
    sudo ln -fs $PWD/memo /usr/local/bin/memo
    sudo ln -fs $PWD/task /usr/local/bin/task
    popd > /dev/null
fi

# dotfiles
~/go/bin/ghq get git@github.com:tm99hjkl/dotfiles.git
ln -fs {$PWD,$HOME}/.bashrc
ln -fs {$PWD,$HOME}/.bash_aliases
ln -fs {$PWD,$HOME}/.config/helix/config.toml
ln -fs {$PWD,$HOME}/.config/helix/languages.toml
ln -fs {$PWD,$HOME}/.config/helix/runtime/themes/tm.toml
ln -fs {$PWD,$HOME}/.inputrc
ln -fs {$PWD,$HOME}/.gitconfig
