#!/usr/bin/env bash
set -ex
sudo apt update

# build-essential
sudo apt install build-essential

# git
sudo apt install git
git clone git@github.com:tm99hjkl/dotfiles ~/ghq/github.com/tm99hjkl/dotfiles || true
cd ~/ghq/github.com/tm99hjkl/dotfiles
ln -fs {$PWD,$HOME}/.gitconfig

# curl
sudo apt install curl

# docker
sudo apt update
sudo apt install ca-certificates
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# go
if ! [ -f /usr/local/go/bin/go ]; then
    curl -LO https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
    rm go1.24.1.linux-amd64.tar.gz
fi

# cargo
if ! [ -f ~/.cargo/bin/cargo ]; then
    curl https://sh.rustup.rs -sSf | sh
fi

# uv
if ! [ -f ~/.local/bin/uv ]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

# ruby
sudo apt install ruby-full

# ghq
/usr/local/go/bin/go install github.com/x-motemen/ghq@latest

# lazygit
/usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

# helix
~/go/bin/ghq get https://github.com/helix-editor/helix
pushd ~/ghq/github.com/helix-editor/helix > /dev/null
git pull
~/.cargo/bin/cargo install --path helix-term --locked
mkdir -p ~/.config/helix/
ln -Tfs $PWD/runtime ~/.config/helix/runtime
popd > /dev/null
ln -fs {$PWD,$HOME}/.config/helix/config.toml
ln -fs {$PWD,$HOME}/.config/helix/languages.toml
ln -fs {$PWD,$HOME}/.config/helix/runtime/themes/tm.toml
~/.cargo/bin/rustup component add rust-analyzer
sudo snap install marksman
sudo apt install python3-pylsp

# wireguard
sudo apt install wireguard

# cloc
sudo apt install cloc

# tmux
sudo apt install tmux
ln -fs {$PWD,$HOME}/.tmux.conf

# tree
sudo apt install tree

# xsel
sudo apt install xsel

# z
~/go/bin/ghq get https://github.com/rupa/z

# memo
if ! [ -d ~/memo ]; then
    pushd ~ > /dev/null
    git clone git@github.com:tm99hjkllogseq/memo
    cd memo
    git config user.name "tm99hjkllogseq"
    git config user.email "tm99hjkllogseq@gmail.com"
    sudo ln -fs $PWD/memo /usr/local/bin/memo
    sudo ln -fs $PWD/task /usr/local/bin/task
    popd > /dev/null
fi

# other dotfiles
ln -fs {$PWD,$HOME}/.bashrc
ln -fs {$PWD,$HOME}/.bash_aliases
ln -fs {$PWD,$HOME}/.inputrc
