"attribute" = "plain_fg"
"type" = { fg = "special", modifiers = ["bold"] }
"constructor" = "special"
"constant" = "plain_fg"
"string" = "#afffff"
"comment" = "#888888"
"variable" = "plain_fg"
"label" = "plain_fg"
"punctuation" = "#888888"
"keyword" = { fg = "#ffffff", modifiers = ["bold"] }
"operator" = "#F92672"
"function" = { fg = "special", modifiers = ["bold"] }
"function.builtin" = { fg = "special", modifiers = ["bold"] }
"tag" = "plain_fg"
"namespace" = "plain_fg"
"special" = "plain_fg"
"markup" = "plain_fg"
"diff" = "plain_fg"

"ui.background" = { fg = "plain_fg", bg = "plain_bg" }
"ui.background.separator" = "plain_fg"
"ui.cursor" = { fg = "plain_fg", modifiers = ["reversed"] }
# "ui.cursor.normal" =
# "ui.cursor.insert" =
# "ui.cursor.select" =
"ui.cursor.match" = { fg = "#666666", modifiers = ["reversed"]}
# "ui.cursor.primary" =
# "ui.cursor.primary.normal" =
# "ui.cursor.primary.insert" =
# "ui.cursor.primary.select" =
# "ui.debug.breakpoint" =
# "ui.debug.active" =
# "ui.gutter" =
# "ui.gutter.selected" =
# "ui.highlight.frameline" =
"ui.linenr" = "#777777"
"ui.linenr.selected" = "plain_fg"
"ui.statusline" = { fg = "plain_fg", bg = "#222222" }
"ui.statusline.inactive" = { fg = "#777777", bg = "#222222" }
# "ui.statusline.normal" =
# "ui.statusline.insert" =
# "ui.statusline.select" =
# "ui.statusline.separator" =
# "ui.bufferline" =
# "ui.bufferline.active" =
# "ui.bufferline.background" =
"ui.popup" = { fg = "plain_fg", bg = "#222222" }
"ui.popup.info" = { fg = "plain_fg", bg = "#222222"}
"ui.window" = "plain_fg"
"ui.help" = { fg = "plain_fg", bg = "#222222" }
"ui.text" = "plain_fg"
"ui.text.focus" = { bg = "#444444" }
"ui.text.inactive" = { fg = "#aaaaaa", bg = "plain_bg" }
"ui.text.info" = { fg = "plain_fg", bg = "#222222" }
"ui.virtual.ruler" = { bg = "plain_bg"}
# "ui.virtual.whitespace" =
# "ui.virtual.indent-guide" =
# "ui.virtual.inlay-hint" =
# "ui.virtual.inlay-hint.parameter" =
# "ui.virtual.inlay-hint.type" =
"ui.virtual.wrap" = "#777777"
# "ui.virtual.jump-label" =
"ui.menu" = { fg = "plain_fg", bg = "#222222" }
"ui.menu.selected" = { fg = "plain_fg", bg = "#444444" }
# "ui.menu.scroll" =
"ui.selection" = { bg = "#444444" }
# "ui.selection.primary" =
"ui.highlight" = { bg = "#222222" }
# "ui.cursorline.primary" =
# "ui.cursorline.secondary" =
# "ui.cursorcolumn.primary" =
# "ui.cursorcolumn.secondary" =

# "warning" =
# "error" =
# "info" =
# "hint" =

"diagnostic" = { bg = "plain_bg", modifiers = ["underlined"] }
# "diagnostic.hint" =
# "diagnostic.info" =
# "diagnostic.warning" =
# "diagnostic.error" =
# "diagnostic.unnecessary" =
# "diagnostic.deprecated" =

[palette]
plain_fg = "#f7e6c3"
plain_bg = "#282828"
special = "#98fb98"
