"attribute" = "#f7e6c3"

"type" = { fg = "#ffffff", modifiers = ["bold"] }

"constructor" = "#87ffaf"

"constant" = "#afffff"
"string" = "#afffff"

"comment" = "#8ec07c"

"variable" = "#f7e6c3"
"variable.parameter" = { fg = "#afffff" }
"variable.builtin" = { fg = "#afffff" }

"label" = "#f7e6c3"

"punctuation" = "#888888"

"keyword" = { fg = "#ffffff", modifiers = ["bold", "italic"] }

"operator" = { fg = "#ffffff", modifiers = ["bold"] }

"function" = { fg = "#87ffaf", modifiers = ["bold"] }
"function.builtin" = { fg = "#87ffaf", modifiers = ["bold"] }

"tag" = "#f7e6c3"

"namespace" = "#f7e6c3"

"markup" = "#f7e6c3"
"markup.heading" = { fg = "#afffff", modifiers = ["bold"] }
"markup.list" = "#87ffaf"
"markup.quote" = "#ffffff"
"markup.bold" = { modifiers = ["underlined"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "#8ec07c", modifiers = ["underlined"] }
"markup.raw" = "#ffffff"
"markup.raw.inline" = { bg = "#393939" }

"diff" = "#777777"

"ui.background" = "#f7e6c3"
"ui.background.separator" = "#f7e6c3"
"ui.cursor" = { fg = "#f7e6c3", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "#666666", modifiers = ["reversed"]}
"ui.linenr" = "#666666"
"ui.linenr.selected" = "#ffffff"
"ui.statusline" = { fg = "#ffffff", bg = "#222222", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "#777777", bg = "#222222" }
"ui.popup" = { fg = "#f7e6c3", bg = "#222222" }
"ui.popup.info" = { fg = "#f7e6c3", bg = "#222222"}
"ui.window" = "#f7e6c3"
"ui.help" = { fg = "#f7e6c3", bg = "#222222" }
"ui.text" = "#f7e6c3"
"ui.text.focus" = { bg = "#444444" }
"ui.text.inactive" = { fg = "#aaaaaa", bg = "#282828" }
"ui.text.info" = { fg = "#f7e6c3", bg = "#222222" }
"ui.virtual.ruler" = { bg = "#393939" }
"ui.virtual.inlay-hint" = "#666666"
"ui.virtual.wrap" = "#777777"
"ui.menu" = { fg = "#f7e6c3", bg = "#222222" }
"ui.menu.selected" = { fg = "#f7e6c3", bg = "#444444" }
"ui.selection" = { bg = "#444444" }
"ui.highlight" = { bg = "#222222" }

"warning" = "#fabd2f"
"error" = "#f92672"
"hint" = "#777777"

"diagnostic" = { bg = "#282828", modifiers = ["underlined"] }
