"comment" = { fg = "_grey" }

"keyword" = { fg = "_lightcoral", modifiers = ["bold"] }

"type"            = { fg = "_electricblue", modifiers = ["bold"] }
"constructor"     = { fg = "_electricblue", modifiers = ["bold"] }
"keyword.storage" = { fg = "_electricblue", modifiers = ["bold"] }

"constant" = { fg = "_lightgreen" }
"string"   = { fg = "_lightgreen" }

"attribute"   = { fg = "_white" }
"variable"    = { fg = "_white" }
"label"       = { fg = "_white" }
"punctuation" = { fg = "_white" }
"tag"         = { fg = "_white" }
"namespace"   = { fg = "_white" }
"operator"    = { fg = "_white" }
"function"    = { fg = "_white", modifiers = ["bold"] }

"markup"            = { fg = "_white" }
"markup.heading"    = { fg = "_white", modifiers = ["bold", "italic"] }
"markup.list"       = { fg = "_white" }
"markup.quote"      = { fg = "_white" }
"markup.bold"       = { fg = "_white", modifiers = ["bold"] }
"markup.italic"     = { fg = "_white", modifiers = ["italic"] }
"markup.link.url"   = { fg = "_electricblue", modifiers = ["underlined"] }
"markup.raw"        = { fg = "_white" }
"markup.raw.inline" = { fg = "_white", bg = "_black2" }

"diff.plus"  = { fg = "_lightgreen" }
"diff.minus" = { fg = "_lightcoral" }
"diff.delta" = { fg = "_witchhaze" }

"ui.background"           = { bg = "_black1" }
"ui.background.separator" = { fg = "_white" }
"ui.cursor"               = { fg = "_white", modifiers = ["reversed"] }
"ui.cursor.match"         = { fg = "_grey", modifiers = ["reversed"] }
"ui.linenr"               = { fg = "_grey" }
"ui.linenr.selected"      = { fg = "_white", modifiers = ["bold"] }
"ui.statusline"           = { fg = "_white", bg = "_black2", modifiers = ["bold"] }
"ui.statusline.inactive"  = { fg = "_grey", bg = "_black2" }
"ui.popup"                = { fg = "_white", bg = "_black2" }
"ui.popup.info"           = { fg = "_white", bg = "_black2" }
"ui.window"               = { fg = "_grey" }
"ui.help"                 = { fg = "_white", bg = "_black2" }
"ui.text"                 = { fg = "_white" }
"ui.text.focus"           = { fg = "_white", modifiers = ["bold", "italic"] }
"ui.text.inactive"        = { fg = "_grey", bg = "_black2" }
"ui.text.info"            = { fg = "_white" }
"ui.virtual.ruler"        = { bg = "_black2" }
"ui.virtual.inlay-hint"   = { fg = "_grey", modifiers = ["italic"] }
"ui.virtual.wrap"         = { fg = "_grey" }
"ui.virtual.jump-label"   = { fg = "_darkorange" }
"ui.menu"                 = { fg = "_white", bg = "_black2" }
"ui.menu.selected"        = { fg = "_white", bg = "_dodgerblue" }
"ui.selection"            = { bg = "_dodgerblue" }
"ui.highlight"            = { bg = "_dodgerblue" }

"warning" = { fg = "_witchhaze" }
"error"   = { fg = "_lightcoral" }
"hint"    = { fg = "_electricblue" }

"diagnostic" = { modifiers = ["underlined"] }

[palette]
"_black1"         = "#111111"
"_black2"         = "#222222"
"_white"          = "#ffffff"

"_darkblue"       = "#00007f"
"_navy"           = "#0000ff"
"_green"          = "#007f00"
"_teal"           = "#007f7f"
"_dodgerblue"     = "#007fff"
"_lime"           = "#00ff00"
"_springgreen"    = "#00ff7f"
"_aqua"           = "#00ffff"
"_maroon"         = "#7f0000"
"_purple"         = "#7f007f"
"_electricindigo" = "#7f00ff"
"_olive"          = "#7f7f00"
"_grey"           = "#7f7f7f"
"_lightslateblue" = "#7f7fff"
"_chartreuse"     = "#7fff00"
"_lightgreen"     = "#7fff7f"
"_electricblue"   = "#7fffff"
"_red"            = "#ff0000"
"_deeppink"       = "#ff007f"
"_fuchsia"        = "#ff00ff"
"_darkorange"     = "#ff7f00"
"_lightcoral"     = "#ff7f7f"
"_fuchsiapink"    = "#ff7fff"
"_yellow"         = "#ffff00"
"_witchhaze"      = "#ffff7f"
