theme = "nord"

[editor]
rulers = [80]
bufferline = "always"
color-modes = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
# character = " "
character = "╎"
skip-levels = 0

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
A-q = ":bp"
A-w = ":bn"
A-c = ":bc"

[keys.insert]
j = {k = "normal_mode"}
C-f = "move_char_right"
C-b = "move_char_left"
C-a = "goto_line_start"
C-e = "goto_line_end"
C-n = "move_visual_line_down"
C-p = "move_visual_line_up"

A-q = ":bp"
A-w = ":bn"
A-c = ":bc"

