theme = "catppuccin_frappe"

[editor]
true-color = true
mouse = false
cursorline = true
rulers = [80]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
A-q = ":bp"
A-w = ":bn"
A-c = ":bc"

[keys.insert]
j = {k = "normal_mode"}
A-q = ":bp"
A-w = ":bn"
A-c = ":bc"

