theme = "base16_transparent"

[editor]
mouse = false
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.insert]
j = {k = "normal_mode"}
