[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 8, unit = "        "}
language-servers = [ { name = "clangd", except-features = [ "diagnostics" ] } ]

[[language]]
name = "latex"
text-width = 72
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "markdown"
text-width = 72
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "python"
language-servers = [ { name = "pylsp" , except-features = [ "diagnostics" ] } ]
